### ISSUE TITLE
Failed to detect namespace or namespace is empty for project

### ISSUE THREAD

**Issue by whydrae** [ui5-community/generator-ui5-library#22]
Hi colleagues,

Following the recent devtoberfest recording (thanks for that!), I used yeoman to generate a library. Right after the generation, I tried to start the library, but got the following error: `Failed to detect namespace or namespace is empty for project my.library`. Could you please take a look?

![img](https://github.com/ui5-community/generator-ui5-library/assets/19683635/f9c12ae7-3fd2-46c5-94b0-52155b256a11)

Output of `ui5 serve --verbose`:

```
Error Message:
Failed to detect namespace or namespace is empty for project my.library. Check verbose log for details.

Stack Trace:
Error: Failed to detect namespace or namespace is empty for project my.library. Check verbose log for details.
    at Library._getNamespace (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/types/Library.js:333:10)
    at async Library._parseConfiguration (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/types/Library.js:169:21)
    at async Library.init (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/Project.js:38:3)
    at async file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/Module.js:165:17
    at async Promise.all (index 0)
    at async Module._getSpecifications (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/Module.js:160:17)
    at async projectGraphBuilder (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:118:61)
    at async graphFromPackageDependencies (file:///E:/Dev/my.library/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/graph.js:73:23)
    at async serve.handler (file:///E:/Dev/my.library/node_modules/@ui5/cli/lib/cli/commands/serve.js:100:11)
```

**Comment by JarkkoRissanen** [comment]
Hello,

I'm not sure if it was intentional, but my ".library" file was named "_.library." After changing that, the project built successfully right after generation.

**Comment by petermuessig** [comment]
Hi @whydrae , very sorry to notice this issue that late. You are running on a Windows machine, right? I have no problems on Mac - maybe this is related to the OS.

Can you share the complete log creating the library:

```sh
> ~  % yo easy-ui5 library

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.6.3 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

                                                               
? What is the namespace of your library? my.library
? Which framework do you want to use? OpenUI5
? Which framework version do you want to use? 1.120.0
? Would you like to omit the namespace in the src and test folder? Yes
? Who is the author of the application? xxx
? Would you like to create a new directory for the application? Yes
? Would you like to initialize a local github repository for the application? No
    force my.library/.yo-rc.json
   create my.library/ui5.yaml
   create my.library/ui5-dist.yaml
   create my.library/package.json
   create my.library/karma.conf.js
   create my.library/karma-ci.conf.js
   create my.library/karma-ci-cov.conf.js
   create my.library/.gitignore
   create my.library/.eslintrc.json
   create my.library/.editorconfig
   create my.library/README.md
   create my.library/LICENSE
   create my.library/test/Example.js
   create my.library/test/Example.html
   create my.library/test/qunit/testsuite.qunit.js
   create my.library/test/qunit/testsuite.qunit.html
   create my.library/test/qunit/Example.qunit.js
   create my.library/src/messagebundle.properties
   create my.library/src/library.js
   create my.library/src/.library
   create my.library/src/ExampleRenderer.js
   create my.library/src/Example.js
   create my.library/src/themes/base/library.source.less
   create my.library/src/themes/base/Example.less
   create my.library/src/themes/sap_horizon/library.source.less
   create my.library/src/themes/sap_horizon_dark/library.source.less
   create my.library/src/themes/sap_horizon_hcw/library.source.less
   create my.library/src/themes/sap_horizon_hcb/library.source.less
   create my.library/src/themes/sap_fiori_3/library.source.less
   create my.library/src/themes/sap_fiori_3_dark/library.source.less
   create my.library/src/themes/sap_fiori_3_hcw/library.source.less
   create my.library/src/themes/sap_fiori_3_hcb/library.source.less

added 1254 packages, and audited 1255 packages in 43s

147 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
    force my.library/.yo-rc.json
> ~  % cd my.library 
> ~/my.library  % ui5 serve
INFO: Using local @ui5/cli installation

info graph:helpers:ui5Framework Using OpenUI5 version: 1.120.0
info server:custom-middleware:ui5-middleware-livereload Livereload server started!
Server started
URL: http://localhost:8080
```

In my case, I see that a `.library` file has been created - as @JarkkoRissanen mentioned this may be the issue to not retrieve the namespace...

**Comment by petermuessig** [comment]
Ok, it is an OS issue - found it:
https://github.com/ui5-community/generator-ui5-library/blob/main/generators/app/index.js#L172

The last replace uses the linux file separators... This won't work on Windows.

Thanks for catching this issue and reporting it.

I will fix it now

**Comment by akudev** [comment]
@petermuessig @whydrae I just had the same error on Mac with the newest version of this repo.

Funnily it only occurred in zsh, not in the JS debug terminal, hence I figured it was related to the respective environment - i.e. the @ui5/cli version installed globally. Indeed the breaking one had globally 3.7.3 and the working one 3.8.0. After updating the globally installed @ui5/cli to 3.8, it also worked in zsh.

In essence: when this still happens, make sure to use the newest @ui5/cli.
